# Generated by Django 5.2.5 on 2025-09-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('fio', models.CharField(blank=True, max_length=255, null=True)),
                ('hemis_id', models.BigIntegerField(db_index=True, unique=True)),
                ('pnfl', models.CharField(blank=True, max_length=25, null=True)),
                ('tg_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.BigIntegerField(db_index=True, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
                'db_table': 'telegram_group',
            },
        ),
        migrations.CreateModel(
            name='HemisTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hemis_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('fio', models.CharField(max_length=255)),
                ('born', models.DateField(blank=True, null=True)),
                ('passport', models.CharField(max_length=9)),
                ('pnfl', models.CharField(db_index=True, max_length=14)),
                ('course', models.CharField(max_length=100)),
                ('student_group', models.CharField(max_length=255)),
                ('in_group', models.BooleanField(default=False)),
                ('register', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hemis_data', to='core.register')),
            ],
            options={
                'verbose_name': 'Hemis Record',
                'verbose_name_plural': 'Hemis Table',
                'db_table': 'hemis_table',
            },
        ),
        migrations.AddField(
            model_name='register',
            name='register_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.telegramgroup'),
        ),
    ]
