# Generated by Django 5.2.5 on 2025-08-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_id', models.BigIntegerField(db_index=True, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
                'db_table': 'telegram_group',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('fio', models.CharField(max_length=255, null=True)),
                ('register_group_id', models.BigIntegerField(db_index=True, unique=True)),
                ('pnfl', models.BigIntegerField(null=True, unique=True)),
                ('tg_tel', models.CharField(max_length=15, null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('parent_tel', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Register',
                'db_table': 'register',
            },
            bases=('core.basemodel',),
        ),
    ]
