# Generated by Django 5.2.5 on 2025-08-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HemisTable',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.basemodel')),
                ('hemis_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.register')),
                ('fio', models.CharField(max_length=255)),
                ('course', models.IntegerField()),
                ('major', models.CharField(max_length=255)),
                ('student_group', models.CharField(max_length=100)),
            ],
            bases=('core.basemodel',),
        ),
    ]
