# Generated by Django 5.2.5 on 2025-08-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register', 'verbose_name_plural': 'Registers'},
        ),
        migrations.RemoveField(
            model_name='register',
            name='register_group_id',
        ),
        migrations.AddField(
            model_name='register',
            name='register_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.telegramgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='parent_tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='pnfl',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='tg_tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
