# Generated by Django 5.2.5 on 2025-08-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hemistable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hemistable',
            options={'verbose_name_plural': 'Hemis Table'},
        ),
        migrations.AlterModelTable(
            name='hemistable',
            table='hemis_table',
        ),
    ]
