# Generated by Django 5.2.5 on 2025-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_register_hemis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hemistable',
            name='in_group',
        ),
        migrations.AddField(
            model_name='hemistable',
            name='in_group',
            field=models.ManyToManyField(blank=True, related_name='hemis_members', to='core.telegramgroup'),
        ),
    ]
