# Generated by Django 5.2.5 on 2025-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_register_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
