# Generated by Django 5.2.5 on 2025-09-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hemistable_in_group_hemistable_in_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hemistable',
            old_name='in_group',
            new_name='telegram_groups',
        ),
    ]
