# Generated by Django 5.2.5 on 2025-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_in_group_hemistable_telegram_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pnfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
