# Generated by Django 5.2.5 on 2025-09-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_register_pnfl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='register_group',
        ),
        migrations.AddField(
            model_name='register',
            name='register_group',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.telegramgroup'),
        ),
    ]
