# Generated by Django 5.2.5 on 2025-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_register_register_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hemistable',
            options={'verbose_name': 'Hemis Record', 'verbose_name_plural': 'Hemis Records'},
        ),
        migrations.RenameField(
            model_name='register',
            old_name='register_group',
            new_name='register_groups',
        ),
        migrations.RenameField(
            model_name='telegramgroup',
            old_name='added_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hemistable',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hemistable',
            name='pnfl',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='pnfl',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='hemistable',
            index=models.Index(fields=['hemis_id', 'pnfl'], name='hemis_table_hemis_i_72315f_idx'),
        ),
        migrations.AddIndex(
            model_name='hemistable',
            index=models.Index(fields=['fio', 'student_group'], name='hemis_table_fio_c70674_idx'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['telegram_id', 'is_active'], name='register_telegra_33e6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['hemis_id', 'pnfl'], name='register_hemis_i_e902a9_idx'),
        ),
    ]
