# Generated by Django 5.2.5 on 2025-09-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hemistable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('join', 'Kirdi'), ('leave', 'Chiqdi'), ('kicked', 'Chiqarildi'), ('removed', "O'chirildi")], help_text='Faoliyat turi (kirdi/chiqdi/chiqarildi)', max_length=10)),
                ('action_by', models.CharField(choices=[('self', "O'zi"), ('admin', 'Admin'), ('system', 'Tizim'), ('invite_link', 'Invite Link')], help_text='Kim tomonidan amalga oshirildi', max_length=15)),
                ('admin_telegram_id', models.BigIntegerField(blank=True, help_text='Actionni amalga oshirgan admin telegram ID si', null=True)),
                ('admin_name', models.CharField(blank=True, help_text='Admin ismi', max_length=255, null=True)),
                ('admin_username', models.CharField(blank=True, help_text='Admin username', max_length=255, null=True)),
                ('activity_time', models.DateTimeField(help_text='Telegram eventdan kelgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Database ga yozilgan vaqt')),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha ma'lumotlar")),
                ('register', models.ForeignKey(help_text="Foydalanuvchi ma'lumotlari", on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.register')),
                ('telegram_group', models.ForeignKey(help_text="Telegram guruh ma'lumotlari", on_delete=django.db.models.deletion.CASCADE, related_name='member_activities', to='core.telegramgroup')),
            ],
            options={
                'verbose_name': "A'zo faoliyati",
                'verbose_name_plural': "A'zolar faoliyati",
                'db_table': 'member_activities',
                'ordering': ['-activity_time'],
                'indexes': [models.Index(fields=['register', 'activity_time'], name='member_acti_registe_d7fdb3_idx'), models.Index(fields=['telegram_group', 'activity_time'], name='member_acti_telegra_24e19e_idx'), models.Index(fields=['activity_type', 'activity_time'], name='member_acti_activit_3c41e9_idx')],
            },
        ),
    ]
